export const ABAC_CACHE_KEYS = {
  ACTIVE_POLICY: 'ABAC_ACTIVE_POLICY',
  POLICIES: 'ABAC_POLICIES',
  POLICY: 'ABAC_POLICY',
  RULES: 'ABAC_RULES',
  DEFINITIONS: 'ABAC_DEFINITIONS',
  DISCOVERY: 'ABAC_DISCOVERY',
} as const
