# EDC Configuration
#
# This file allows system administrators to preconfigure an EDC.
# Place this file at:
# - Development: /aas-web-ui/public/config/edc.yml
# - Production (Docker): Mount to /edc.yml

# EDC example Configuration
# edc:
#   type: '...'
#   controlplane:
#     endpoint: "http://localhost:8080"
#     managementEndpoint: "http://localhost:8081"
#     dspEndpoint: "http://localhost:8084/api/v1/dsp"
#   security:
#     type: Key
#     config:
#       key: "xApiKey"
#   dataspace:
#     ssi_host: "ssi.datasapce.host"
#   business-partners:
#     - name: "BP Name"
#       bpn: "BPN"
#       dsp: "BP DSP"

# EDC example Configuration
# edc:
#   type: '...'
#   controlplane:
#     endpoint: "http://localhost:8080"
#     managementEndpoint: "http://localhost:8081"
#     dspEndpoint: "http://localhost:8084/api/v1/dsp"
#   security:
#     type: Token
#     config:
#       url: "http://localhost:5432"
#       clientId: "clientId"
#       clientSecret: "clientSecret"
#   dataspace:
#     ssi_host: "ssi.datasapce.host"
#   business-partners:
#     - name: "BP Name"
#       bpn: "BPN"
#       dsp: "BP DSP"
