services:
  db-infra1:
    image: postgres:18.4
    container_name: postgres-infra1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxInfra1
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxInfra1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  basyx-configuration-infra1:
    image: eclipsebasyx/basyxconfigurationservice-go:SNAPSHOT
    pull_policy: always
    container_name: basyx-configuration-infra1
    environment:
      POSTGRES_HOST: db-infra1
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DBNAME: basyxInfra1
      POSTGRES_MAXOPENCONNECTIONS: 500
      POSTGRES_MAXIDLECONNECTIONS: 500
      POSTGRES_CONNMAXLIFETIMEMINUTES: 5
    depends_on:
      db-infra1:
        condition: service_healthy
    networks:
      - multiple-infrastructures

  keycloak:
    image: keycloak/keycloak:26.6.4
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-infra1:5432/basyxInfra1
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin123
      KC_HOSTNAME: keycloak.localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_MANAGEMENT_ENABLED: "true"
    command: ["start-dev", "--import-realm", "--health-enabled=true"]
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import:ro
    depends_on:
      db-infra1:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  keycloak-healthcheck:
    image: curlimages/curl:8.17.0
    container_name: keycloak-healthcheck
    command: >
      sh -c "until curl -sf http://keycloak:9000/health/ready; do sleep 5; done"
    depends_on:
      - keycloak
    networks:
      - multiple-infrastructures

  aas-env-infra1:
    image: eclipsebasyx/aasenvironment-go:SNAPSHOT
    pull_policy: always
    container_name: secured-aas-env
    command: ["/app/aasenvironmentservice"]
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      CORS_ALLOWEDORIGINS: "*"
      CORS_ALLOWEDHEADERS: "*"
      CORS_ALLOWEDCREDENTIALS: "true"
      CORS_ALLOWEDMETHODS: GET,POST,PUT,PATCH,DELETE,OPTIONS
      POSTGRES_HOST: db-infra1
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DBNAME: basyxInfra1
      POSTGRES_MAXOPENCONNECTIONS: 500
      POSTGRES_MAXIDLECONNECTIONS: 500
      POSTGRES_CONNMAXLIFETIMEMINUTES: 5
      ABAC_ENABLED: "true"
      ABAC_MODELPATH: /security_env/access-rules.json
      ABAC_POLICY_FILE_IMPORT: if_missing
      OIDC_TRUSTLISTPATH: /security_env/trustlist.json
      GENERAL_AASREGISTRYINTEGRATION: "true"
      GENERAL_SUBMODELREGISTRYINTEGRATION: "true"
      GENERAL_DISCOVERYINTEGRATION: "true"
      GENERAL_EXTERNALURL: http://localhost:8081
      GENERAL_AAS_PRECONFIG_PATHS: /app/preconfiguration
    volumes:
      - ./aas:/app/preconfiguration:ro
      - ./security_env:/security_env:ro
    depends_on:
      basyx-configuration-infra1:
        condition: service_completed_successfully
      keycloak-healthcheck:
        condition: service_completed_successfully
    extra_hosts:
      - "keycloak.localhost:host-gateway"
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  influxdb-infra1:
    image: influxdb:2
    container_name: influxdb-infra1
    ports:
      - "8086:8086"
      - "9999:9999"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: influxpassword
      DOCKER_INFLUXDB_INIT_ORG: basyx
      DOCKER_INFLUXDB_INIT_BUCKET: basyx
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q=="
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  telegraf-infra1:
    image: telegraf:1.29.1
    container_name: telegraf-infra1
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    hostname: basyx_host
    depends_on:
      - influxdb-infra1
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  mosquitto-infra1:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto-infra1
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto:/mosquitto
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3"]
      interval: 5s
      timeout: 10s
      start_period: 1s
      retries: 3
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  mqtt-publisher-infra1:
    build: ./mqtt-publisher
    container_name: mqtt-publisher-infra1
    depends_on:
      mosquitto-infra1:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - multiple-infrastructures
