services:
  db-infra2:
    image: postgres:18.4
    container_name: postgres-infra2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxInfra2
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxInfra2"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  basyx-configuration-infra2:
    image: eclipsebasyx/basyxconfigurationservice-go:SNAPSHOT
    pull_policy: always
    container_name: basyx-configuration-infra2
    environment:
      POSTGRES_HOST: db-infra2
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DBNAME: basyxInfra2
      POSTGRES_MAXOPENCONNECTIONS: 500
      POSTGRES_MAXIDLECONNECTIONS: 500
      POSTGRES_CONNMAXLIFETIMEMINUTES: 5
    depends_on:
      db-infra2:
        condition: service_healthy
    networks:
      - multiple-infrastructures

  aas-env-infra2:
    image: eclipsebasyx/aasenvironment-go:SNAPSHOT
    pull_policy: always
    container_name: aas-env-infra2
    command: ["/app/aasenvironmentservice"]
    ports:
      - "9081:8081"
    environment:
      SERVER_PORT: 8081
      CORS_ALLOWEDORIGINS: "*"
      CORS_ALLOWEDHEADERS: "*"
      CORS_ALLOWEDCREDENTIALS: "true"
      CORS_ALLOWEDMETHODS: GET,POST,PUT,PATCH,DELETE,OPTIONS
      POSTGRES_HOST: db-infra2
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DBNAME: basyxInfra2
      POSTGRES_MAXOPENCONNECTIONS: 500
      POSTGRES_MAXIDLECONNECTIONS: 500
      POSTGRES_CONNMAXLIFETIMEMINUTES: 5
      ABAC_ENABLED: "false"
      GENERAL_AASREGISTRYINTEGRATION: "true"
      GENERAL_SUBMODELREGISTRYINTEGRATION: "true"
      GENERAL_DISCOVERYINTEGRATION: "true"
      GENERAL_EXTERNALURL: http://localhost:9081
      GENERAL_AAS_PRECONFIG_PATHS: /app/preconfiguration/BOMAAS.aasx,/app/preconfiguration/FileHandlingAAS.aasx,/app/preconfiguration/IESEDriveMotorDM3000.aasx,/app/preconfiguration/IFCShell.aasx,/app/preconfiguration/SensorExampleComplete.aasx
    volumes:
      - ./aas:/app/preconfiguration:ro
    depends_on:
      basyx-configuration-infra2:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  nodered-infra2:
    build: ./nodered
    container_name: nodered-infra2
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    depends_on:
      aas-env-infra2:
        condition: service_healthy
      mosquitto-infra2:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  mosquitto-infra2:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto-infra2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3"]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s
    restart: unless-stopped
    networks:
      - multiple-infrastructures

  mqtt-client-infra2:
    build: ./mqtt-client
    container_name: mqtt-client-infra2
    depends_on:
      mosquitto-infra2:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - multiple-infrastructures
