import { createPinia, setActivePinia } from 'pinia';
import { describe, expect, it } from 'vitest';
import { useReferableUtils } from '@/composables/AAS/ReferableUtils';

const pinia = createPinia();
setActivePinia(pinia); // Activate Pinia for the test environment

const { checkIdShort, descriptionToDisplay, nameToDisplay } = useReferableUtils();

describe("ReferableUtils.ts; Tests for 'nameToDisplay()'", () => {
    // Define test data for nameToDisplay()
    const nameToDisplayTestData = [
        {
            testId: '56212d7a-00ca-4b2e-8168-c14b5ea8dae9',
            referable: null,
            defaultNameToDisplay: '',
            result: '',
        },
        {
            testId: '356c222d-9383-4faa-8483-b0772dd08685',
            referable: null,
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'fc3cc67f-f825-45aa-ad67-734978d5b782',
            referable: {},
            defaultNameToDisplay: '',
            result: '',
        },
        {
            testId: '817a24ee-aa6f-49b7-8d5e-553d513da57d',
            referable: {},
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '9e20d66a-9564-41e4-ab04-d35fe03aa153',
            referable: { id: 'fooBarId' },
            defaultNameToDisplay: '',
            result: 'fooBarId',
        },
        {
            testId: 'f2d8ad07-57ac-404c-b07a-ea9ed2157c29',
            referable: { id: 'fooBarId' },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'cb0a5aba-658f-4159-8ff3-fccb335e4bf0',
            referable: { idShort: 'fooBarIdShort' },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '4ee522e6-2328-4770-8324-e28cdf0425d4',
            referable: { idShort: 'fooBarIdShort' },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '18fa0407-3abd-4b91-a9ea-3136f91bed40',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort' },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '9ca168ee-898f-4c3d-834a-87d12d39a8b8',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort' },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'ba01f25c-d5b9-41f8-b2e0-f9f37fdc7186',
            referable: { displayName: null },
            defaultNameToDisplay: '',
            result: '',
        },
        {
            testId: 'bf266b75-e65c-407a-b288-1b49458162fb',
            referable: { displayName: null },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '462a7919-645f-4e20-aeac-ea8d79783478',
            referable: { id: 'fooBarId', displayName: null },
            defaultNameToDisplay: '',
            result: 'fooBarId',
        },
        {
            testId: '559c56f8-048c-4db1-be2f-db01aa2e9c7f',
            referable: { id: 'fooBarId', displayName: null },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '16646eb3-5069-4752-96eb-3affb1cd58a2',
            referable: { idShort: 'fooBarIdShort', displayName: null },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '479dd3a8-409e-4ccf-b234-9381d5c304ce',
            referable: { idShort: 'fooBarIdShort', displayName: null },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '6729cdcd-7bea-4651-a1fd-9ad9413bfd6c',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: null },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '05f29504-6310-4933-b132-8e004e8234b4',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: null },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '58e241c7-bb70-458f-836e-0a4305d6fa40',
            referable: { displayName: [] },
            defaultNameToDisplay: '',
            result: '',
        },
        {
            testId: 'f3175d2a-cf5f-46cc-83e2-79365071ff47',
            referable: { displayName: [] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '2e76d269-5a0b-4821-86a5-c735ab128e32',
            referable: { id: 'fooBarId', displayName: [] },
            defaultNameToDisplay: '',
            result: 'fooBarId',
        },
        {
            testId: '63f33b47-ec10-462a-bc23-689bc4d2c6df',
            referable: { id: 'fooBarId', displayName: [] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'daec92cb-eaa1-4f2c-9589-b13618898fe7',
            referable: { idShort: 'fooBarIdShort', displayName: [] },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '7e4cdaa0-629e-4abc-ba79-8b7893652dd0',
            referable: { idShort: 'fooBarIdShort', displayName: [] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '10f15523-cb72-4aad-b2f6-85fd2d177f9c',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: [] },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '78ff572d-ffcf-414c-8648-33b925c1f5a4',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: [] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '72754f09-f9e7-4c81-b186-8946f52ab9f5',
            referable: { displayName: [{}] },
            defaultNameToDisplay: '',
            result: '',
        },
        {
            testId: '23e14737-9682-4b99-b018-aca394e16e1a',
            referable: { displayName: [{}] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '21c91697-4936-4b33-992f-dd2c560d00c9',
            referable: { id: 'fooBarId', displayName: [{}] },
            defaultNameToDisplay: '',
            result: 'fooBarId',
        },
        {
            testId: 'b3c781ac-302e-4330-bb23-c4e51ab8307e',
            referable: { id: 'fooBarId', displayName: [{}] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '122a2406-7eae-433f-9180-10b95386e723',
            referable: { idShort: 'fooBarIdShort', displayName: [{}] },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '862d297d-e112-434c-b943-82171c03b30a',
            referable: { idShort: 'fooBarIdShort', displayName: [{}] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '54f58f52-8c69-49a7-9ff4-5d05d6b3052a',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: [{}] },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: 'e2a453b3-1bf7-4d99-a9d6-3f5c6a4be9f5',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: [{}] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'cd8fe9f0-0393-42e7-9a1d-e76006570c1a',
            referable: { displayName: [{ language: 'en' }] },
            defaultNameToDisplay: '',
            result: '',
        },
        {
            testId: '4e684319-752b-4d4b-83bb-43a250b7f39f',
            referable: { displayName: [{ language: 'en' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'b8a144f7-45aa-404b-b393-52454a67e18c',
            referable: { id: 'fooBarId', displayName: [{ language: 'en' }] },
            defaultNameToDisplay: '',
            result: 'fooBarId',
        },
        {
            testId: 'cdc99cc3-1695-44c8-831b-3b684bf10564',
            referable: { id: 'fooBarId', displayName: [{ language: 'en' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: '9464e584-fa0a-4e13-9d12-9a6ce1a4ddf9',
            referable: { idShort: 'fooBarIdShort', displayName: [{ language: 'en' }] },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '1fc26134-c7a1-4843-a61e-1a7bd87d8dd4',
            referable: { idShort: 'fooBarIdShort', displayName: [{ language: 'en' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'a7512ba2-5ca3-465a-86f2-7d83aab048c6',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: [{ language: 'en' }] },
            defaultNameToDisplay: '',
            result: 'fooBarIdShort',
        },
        {
            testId: '80ade774-5f3c-4a02-b7cb-c54d08018f62',
            referable: { id: 'fooBarId', idShort: 'fooBarIdShort', displayName: [{ language: 'en' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDefaultNameToDisplay',
        },
        {
            testId: 'a91a6573-d372-49a6-aacc-731811cabaa1',
            referable: { displayName: [{ language: 'en', text: 'fooBarDisplayName' }] },
            defaultNameToDisplay: '',
            result: 'fooBarDisplayName',
        },
        {
            testId: '97eb9486-348a-459d-8a99-d686d671f0b7',
            referable: { displayName: [{ language: 'en', text: 'fooBarDisplayName' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDisplayName',
        },
        {
            testId: 'f689b75b-fd8a-42bd-b9b3-fc9c8c14a03a',
            referable: { id: 'fooBarId', displayName: [{ language: 'en', text: 'fooBarDisplayName' }] },
            defaultNameToDisplay: '',
            result: 'fooBarDisplayName',
        },
        {
            testId: 'c3cf0f58-f3e9-43cc-bc64-9a25ef840ec9',
            referable: { id: 'fooBarId', displayName: [{ language: 'en', text: 'fooBarDisplayName' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDisplayName',
        },
        {
            testId: 'ce1f905a-74ec-4415-ae73-f90cb7040cae',
            referable: { idShort: 'fooBarIdShort', displayName: [{ language: 'en', text: 'fooBarDisplayName' }] },
            defaultNameToDisplay: '',
            result: 'fooBarDisplayName',
        },
        {
            testId: '5839bbcc-87a4-4969-b013-46a95d93b316',
            referable: { idShort: 'fooBarIdShort', displayName: [{ language: 'en', text: 'fooBarDisplayName' }] },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDisplayName',
        },
        {
            testId: '0c8449f5-f032-4081-9126-17faf65e7e90',
            referable: {
                id: 'fooBarId',
                idShort: 'fooBarIdShort',
                displayName: [{ language: 'en', text: 'fooBarDisplayName' }],
            },
            defaultNameToDisplay: '',
            result: 'fooBarDisplayName',
        },
        {
            testId: 'fcc9c0cc-8958-4a19-96dc-e1959b731961',
            referable: {
                id: 'fooBarId',
                idShort: 'fooBarIdShort',
                displayName: [{ language: 'en', text: 'fooBarDisplayName' }],
            },
            defaultNameToDisplay: 'fooBarDefaultNameToDisplay',
            result: 'fooBarDisplayName',
        },
    ];

    // Tests for nameToDisplay()
    nameToDisplayTestData.forEach(function (nameToDisplayTestDataset) {
        // Define test data
        const referable = nameToDisplayTestDataset.referable; //e.g. the ID of a ConceptDescription
        const defaultNameToDisplay = nameToDisplayTestDataset.defaultNameToDisplay;
        const result = nameToDisplayTestDataset.result;

        it(`${nameToDisplayTestDataset.testId}: nameToDisplay(${referable}, ${("'" + defaultNameToDisplay + "'").padEnd(30, ' ')}')`, () => {
            // Perform the assertion
            expect(nameToDisplay(referable, 'en', defaultNameToDisplay)).toStrictEqual(result);
        });
    });
});

describe("ReferableUtils.ts; Tests for 'descriptionToDisplay()'", () => {
    // Define test data for descriptionToDisplay()
    const descriptionToDisplayTestData = [
        {
            testId: 'ea837130-188c-461b-91ce-b670b15557ad',
            referable: null,
            defaultDescriptionToDisplay: '',
            result: '',
        },
        {
            testId: '3991237d-ba5d-4e89-b1dd-d4c6b199aa74',
            referable: null,
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDefaultDescriptionToDisplay',
        },
        {
            testId: 'd3f5d840-423e-4db4-b468-7348720158bb',
            referable: {},
            defaultDescriptionToDisplay: '',
            result: '',
        },
        {
            testId: '9a70ee19-0a53-4e5c-849d-2073800caaba',
            referable: {},
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDefaultDescriptionToDisplay',
        },
        {
            testId: 'f23324d0-1760-4cd0-9c52-57f47cfe3d8f',
            referable: { description: null },
            defaultDescriptionToDisplay: '',
            result: '',
        },
        {
            testId: '9cd57996-eec9-4aff-84ce-1cc4eee75bde',
            referable: { description: null },
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDefaultDescriptionToDisplay',
        },
        {
            testId: 'e6551f2b-a7e0-4e16-8749-4677968483a8',
            referable: { description: [] },
            defaultDescriptionToDisplay: '',
            result: '',
        },
        {
            testId: 'f66012e2-dd63-4c0e-a32a-88da945453a7',
            referable: { description: [] },
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDefaultDescriptionToDisplay',
        },
        {
            testId: '6d7ffd3b-ea23-4dea-b065-03e4295ff86e',
            referable: { description: [{}] },
            defaultDescriptionToDisplay: '',
            result: '',
        },
        {
            testId: '20f9250f-356f-4f8c-84cd-b0267d63e6de',
            referable: { description: [{}] },
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDefaultDescriptionToDisplay',
        },
        {
            testId: 'f416ab9b-2374-427e-a985-04c1c44ef23e',
            referable: { description: [{ language: 'en' }] },
            defaultDescriptionToDisplay: '',
            result: '',
        },
        {
            testId: 'fa98c529-ee48-4a85-b61a-885ed53825b0',
            referable: { description: [{ language: 'en' }] },
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDefaultDescriptionToDisplay',
        },
        {
            testId: 'd80c226f-0cf9-4b50-8648-a720d29ec119',
            referable: { description: [{ language: 'en', text: 'fooBarDescription' }] },
            defaultDescriptionToDisplay: '',
            result: 'fooBarDescription',
        },
        {
            testId: '3a8419d3-d369-4f3c-8020-44b250f74f96',
            referable: { description: [{ language: 'en', text: 'fooBarDescription' }] },
            defaultDescriptionToDisplay: 'fooBarDefaultDescriptionToDisplay',
            result: 'fooBarDescription',
        },
    ];

    // Tests for descriptionToDisplay()
    descriptionToDisplayTestData.forEach(function (descriptionToDisplayTestDataset) {
        // Define test data
        const referable = descriptionToDisplayTestDataset.referable; //e.g. the ID of a ConceptDescription
        const defaultDescriptionToDisplay = descriptionToDisplayTestDataset.defaultDescriptionToDisplay;
        const result = descriptionToDisplayTestDataset.result;

        it(`${descriptionToDisplayTestDataset.testId}: descriptionToDisplay(${referable}, 'en', ${("'" + defaultDescriptionToDisplay + "'").padEnd(35, ' ')})`, () => {
            // Perform the assertion
            expect(descriptionToDisplay(referable, 'en', defaultDescriptionToDisplay)).toStrictEqual(result);
        });
    });
});

describe("ReferableUtils.ts; Tests for 'checkIdShort()'", () => {
    // Define test data for checkIdShort()
    const checkIdShortTestData = [
        {
            testId: '42a62525-377b-4173-9003-271eba423039',
            referable: null,
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '4ac67a6c-7319-4ef1-a4f7-b4805c4d04bd',
            referable: null,
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '560a2821-7e88-42b0-97f4-82fd5cb3c55d',
            referable: null,
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '3e6c3742-4bd9-4a76-bd8d-6396d02f6348',
            referable: null,
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '897de1bf-a766-4602-a110-05573c042df0',
            referable: null,
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'c941d586-7442-402d-8c4a-ff0c31157cca',
            referable: null,
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'b18db349-303b-41a6-b3a2-06290f53ce99',
            referable: null,
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: 'af19fea4-a5a6-4e3c-98eb-b75bdb5cf65c',
            referable: null,
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '80257fb0-4f19-4ebb-af4b-72cf3c95d739',
            referable: {},
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '1e412477-cdc4-47fb-8df3-18e311cdfdf4',
            referable: {},
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '8727cb92-e7c6-45c4-a70a-170524a3cf62',
            referable: {},
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '3f12f46a-83b0-4a2e-8c97-c97b164559f5',
            referable: {},
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'abb5c875-db91-495a-a890-2c8c3199a45e',
            referable: {},
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'edd326e1-1b3a-4f4f-82c9-4196de0a94d1',
            referable: {},
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'a308f7f2-2242-4981-9b77-f99825357080',
            referable: {},
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: 'eb69f65c-9338-4b37-b87a-b5d7ab7e49c1',
            referable: {},
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: false,
        },

        {
            testId: 'c7dd4bb1-c909-40f7-84e2-7962d48d22f1',
            referable: { idShort: null },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'a25ad545-cc1a-4990-befe-1266bf0ce7e8',
            referable: { idShort: null },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'b4f41b24-429d-4a5d-87d6-5c220c0fec9b',
            referable: { idShort: null },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '6c48f174-82d5-4e28-a004-124e652e7fbf',
            referable: { idShort: null },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'dcde7b87-4ded-4f93-82a5-b70b21515221',
            referable: { idShort: null },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '6e2a56a4-6222-46b6-b4cd-8253f965e41f',
            referable: { idShort: null },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '0d82ce68-5fe4-4136-9653-326c90c87ab9',
            referable: { idShort: null },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '857ecba3-433b-4bcc-8c2e-63ecf613026e',
            referable: { idShort: null },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: false,
        },

        {
            testId: '8a03f5d5-ebee-49c8-8ee5-645f5a1e47ae',
            referable: { idShort: '' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '8622b20f-e166-415d-84fc-7607b02701ec',
            referable: { idShort: '' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'b85bee74-2241-40fa-b68a-7c16eb181afa',
            referable: { idShort: '' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'e08dc6b2-60c1-4896-b7ed-0785a4217616',
            referable: { idShort: '' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'b02176c5-d575-4784-8e1f-5b236f6ac3c2',
            referable: { idShort: '' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '5c84ebf9-8ed7-48df-bcd5-4e55436dda3f',
            referable: { idShort: '' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '763395a8-e68f-47c7-816d-32d228e357ca',
            referable: { idShort: '' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: 'cdea7e6c-1e50-4f2e-beb5-5104415bda1c',
            referable: { idShort: '' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: false,
        },

        {
            testId: '7a2fa3ae-d039-4e4c-b769-89d8633d0f10',
            referable: { idShort: 'foobarIdShort' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '67f490cf-3679-44a3-9890-6907686a9a01',
            referable: { idShort: 'foobarIdShort' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: true,
        },
        {
            testId: 'fb4083e4-5056-4edd-8cdb-e4895751027a',
            referable: { idShort: 'foobarIdShort' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '2a65f748-245c-47e2-aec7-a773f317294f',
            referable: { idShort: 'foobarIdShort' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: true,
        },
        {
            testId: 'b187c4b9-1459-4eb3-8fb1-478200907a59',
            referable: { idShort: 'foobarIdShort' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '82fc67c5-6d7c-45b2-9dc1-3492954ad972',
            referable: { idShort: 'foobarIdShort' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: true,
        },
        {
            testId: '2396b603-df18-4984-84a9-253fa872d2c0',
            referable: { idShort: 'foobarIdShort' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '4890cf15-c059-4e78-937c-08f790f380bc',
            referable: { idShort: 'foobarIdShort' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: true,
        },

        {
            testId: '7a84d8d2-a29c-46f5-8356-d97bebef3f68',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '5792f72f-627d-48c2-94de-3e0d05c40b1d',
            referable: { idShort: 'foobar{01}' },
            idShort: 'foobar',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '981e1d8b-56cc-453b-9fe2-4f62b091f3f6',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '835ab844-75c4-439f-bc15-584c1d5a1a89',
            referable: { idShort: 'foobar{01}' },
            idShort: 'foobar',
            startsWith: true,
            strict: false,
            result: true,
        },
        {
            testId: 'e3f6238a-81d9-4b1c-a132-9057c9ceecdf',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '2f1e9d2a-1793-4833-b314-9a8eb0577fda',
            referable: { idShort: 'foobar{01}' },
            idShort: 'foobar',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '2a31ccc6-6e3a-4b9a-b5b8-1838d9ffd911',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '618ff2fe-734a-46cb-97b3-828781614ee6',
            referable: { idShort: 'foobar{01}' },
            idShort: 'foobar',
            startsWith: true,
            strict: true,
            result: true,
        },
        {
            testId: 'b86f3d92-7d4d-487e-ac37-3ce3f7b9036a',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '6ae8693b-a36a-4658-a010-3faf0093b443',
            referable: { idShort: 'foobar' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'a8cc5024-2c8a-4ba0-93c6-53c9aa94b023',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'b4af9ef2-0d4d-4748-a88e-8e7e79cb2bf4',
            referable: { idShort: 'foobar' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '3c51fbcb-6855-4230-8451-77bf9202fc09',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '170e1f65-278f-4052-b65e-b32ff0b2df27',
            referable: { idShort: 'foobar' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'cd3cdd42-5def-4ffe-9da4-a093c3ec6cbb',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '7d791469-7f9d-4d7b-86b3-9bdc28ab7e4c',
            referable: { idShort: 'foobar' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: false,
        },

        {
            testId: 'df823d9d-eceb-4334-9541-8e85834f73b6',
            referable: { idShort: 'FooBar{01}' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'deea0fe5-4021-4ee5-a821-a708eee09e75',
            referable: { idShort: 'FooBar{01}' },
            idShort: 'foobar',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'fd03d13b-38d8-412b-a772-5e38098bc917',
            referable: { idShort: 'FooBar{01}' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'db1e6225-944b-416a-baec-2782d26a7419',
            referable: { idShort: 'FooBar{01}' },
            idShort: 'foobar',
            startsWith: true,
            strict: false,
            result: true,
        },
        {
            testId: 'a498efd2-f7c0-4c62-8b98-4d164418ac62',
            referable: { idShort: 'FooBar{01}' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '68275d59-7db4-499d-8362-6f56a161ff7a',
            referable: { idShort: 'FooBar{01}' },
            idShort: 'foobar',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'be91d9ec-dbf1-4ca7-a7fc-f2942af89452',
            referable: { idShort: 'FooBar{01}' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '3151abcd-e784-4d41-aaf2-786e36bed214',
            referable: { idShort: 'FooBar{01}' },
            idShort: 'foobar',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '826b8cb2-9ffd-4797-a24e-83c2dc99abb4',
            referable: { idShort: 'FooBar' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '5253d683-e941-4d26-9579-c834e17e045f',
            referable: { idShort: 'FooBar' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'c237ca7d-c6b4-4f17-aa86-af40219e4ac7',
            referable: { idShort: 'FooBar' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'f550d90d-d7af-456a-a2a2-70123f45bd11',
            referable: { idShort: 'FooBar' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'acace805-e3ed-43ae-99ae-16e212d69103',
            referable: { idShort: 'FooBar' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'd1e9b22f-8bec-4a1d-8b32-afd893c0a8b7',
            referable: { idShort: 'FooBar' },
            idShort: 'foobarIdShort',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'daca124f-9ee0-48c5-bd66-a28e42af5fcf',
            referable: { idShort: 'FooBar' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: 'd264cc3d-d7df-4f42-b75a-7301f2642d34',
            referable: { idShort: 'FooBar' },
            idShort: 'foobarIdShort',
            startsWith: true,
            strict: true,
            result: false,
        },

        {
            testId: 'dc91cdfb-df4b-4b97-bbab-926bdda26ce8',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '0e1b084a-6050-46c3-b9c5-51010381b037',
            referable: { idShort: 'foobar{01}' },
            idShort: 'FooBar',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '50280c04-54aa-4379-8f6e-b588761c4bc1',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: '94737ac0-035b-4462-b1aa-98f2b2b2e550',
            referable: { idShort: 'foobar{01}' },
            idShort: 'FooBar',
            startsWith: true,
            strict: false,
            result: true,
        },
        {
            testId: '0ad7ee2c-cfcd-4f48-93ef-9ad959ed13c8',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: 'cbaef1ad-a8fd-4fb5-898f-9b9bc4cf8acf',
            referable: { idShort: 'foobar{01}' },
            idShort: 'FooBar',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '7e8f8f5a-09e3-4b41-9095-44098f383ecf',
            referable: { idShort: 'foobar{01}' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '1c4963dc-f7a1-44ee-8997-be0abe15ab64',
            referable: { idShort: 'foobar{01}' },
            idShort: 'FooBar',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '6840cccb-91bc-4297-9955-df5fed086208',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: 'e50c77fe-98a1-4807-9915-c1cd59540423',
            referable: { idShort: 'foobar' },
            idShort: 'FooBar{01}',
            startsWith: false,
            strict: false,
            result: false,
        },
        {
            testId: '2cd3ece5-b321-401c-a367-dbcb0ba3c2f9',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'b49e3d58-a45b-4e46-8db2-b909151385ec',
            referable: { idShort: 'foobar' },
            idShort: 'FooBar{01}',
            startsWith: true,
            strict: false,
            result: false,
        },
        {
            testId: 'b5e38293-5d36-4396-a0ea-c2422dadce5d',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '632ca0b4-40c9-478f-a67b-602954bfa9d8',
            referable: { idShort: 'foobar' },
            idShort: 'FooBar{01}',
            startsWith: false,
            strict: true,
            result: false,
        },
        {
            testId: '34d65fe2-2ead-44fd-aba7-627e558e6470',
            referable: { idShort: 'foobar' },
            idShort: '',
            startsWith: true,
            strict: true,
            result: false,
        },
        {
            testId: '37505295-d912-4433-b083-2f28c18a2a84',
            referable: { idShort: 'foobar' },
            idShort: 'FooBar{01}',
            startsWith: true,
            strict: true,
            result: false,
        },
    ];

    // Tests for checkIdShort()
    checkIdShortTestData.forEach(function (checkIdShortTestDataset) {
        // Define test data
        const referable = checkIdShortTestDataset.referable; // e.g. the ID of a ConceptDescription
        const idShort = checkIdShortTestDataset.idShort;
        const startsWith = checkIdShortTestDataset.startsWith;
        const strict = checkIdShortTestDataset.strict;
        const result = checkIdShortTestDataset.result;

        it(`${checkIdShortTestDataset.testId}: checkIdShort(${referable}, ${("'" + idShort + "'").padEnd(15, ' ')}, startsWith = ${startsWith.toString().padEnd(5, ' ')}, strict = ${strict.toString().padEnd(5, ' ')})`, () => {
            // Perform the assertion
            expect(checkIdShort(referable, idShort, startsWith, strict)).toStrictEqual(result);
        });
    });
});
