include:
  - ./Infrastructure1/docker-compose-infra1.yml
  - ./Infrastructure2/docker-compose-infra2.yml

services:
  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    pull_policy: always
    container_name: aas-web-ui
    ports:
      - "3000:3000"
    volumes:
      - ./basyx-infra.yml:/basyx-infra.yml:ro
    environment:
      ENDPOINT_CONFIG_AVAILABLE: "true"
      INFLUXDB_TOKEN: "S18VeAlq042B4naMX31oqIaSGmUmOLAC-DV3VIdkxDJuAhTXLTVFEchyTSmCcUAmB7Wu94KgExzV8gJaDjzR3Q=="
    restart: unless-stopped
    networks:
      - multiple-infrastructures

networks:
  multiple-infrastructures:
    name: basyx-multi-infrastructures
    driver: bridge
