const vueRuntimeAutoImports = [
  'EffectScope',
  'computed',
  'createApp',
  'customRef',
  'defineAsyncComponent',
  'defineComponent',
  'effectScope',
  'getCurrentInstance',
  'getCurrentScope',
  'getCurrentWatcher',
  'h',
  'inject',
  'isProxy',
  'isReactive',
  'isReadonly',
  'isRef',
  'isShallow',
  'markRaw',
  'nextTick',
  'onActivated',
  'onBeforeMount',
  'onBeforeUnmount',
  'onBeforeUpdate',
  'onDeactivated',
  'onErrorCaptured',
  'onMounted',
  'onRenderTracked',
  'onRenderTriggered',
  'onScopeDispose',
  'onServerPrefetch',
  'onUnmounted',
  'onUpdated',
  'onWatcherCleanup',
  'provide',
  'reactive',
  'readonly',
  'ref',
  'resolveComponent',
  'shallowReactive',
  'shallowReadonly',
  'shallowRef',
  'toRaw',
  'toRef',
  'toRefs',
  'toValue',
  'triggerRef',
  'unref',
  'useAttrs',
  'useCssModule',
  'useCssVars',
  'useId',
  'useModel',
  'useSlots',
  'useTemplateRef',
  'watch',
  'watchEffect',
  'watchPostEffect',
  'watchSyncEffect',
]

const vueTypeAutoImports = [
  'Component',
  'ComponentPublicInstance',
  'ComputedRef',
  'DirectiveBinding',
  'ExtractDefaultPropTypes',
  'ExtractPropTypes',
  'ExtractPublicPropTypes',
  'InjectionKey',
  'MaybeRef',
  'MaybeRefOrGetter',
  'PropType',
  'Ref',
  'ShallowRef',
  'Slot',
  'Slots',
  'VNode',
  'WritableComputedRef',
]

const vueAutoImportPreset = {
  from: 'vue',
  imports: [
    ...vueRuntimeAutoImports,
    ...vueTypeAutoImports.map(name => ({ name, type: true })),
  ],
}

export { vueAutoImportPreset, vueRuntimeAutoImports }
